# Generated by Django 5.2.14 on 2026-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discription',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
