# Generated by Django 5.2.14 on 2026-06-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='discription',
            new_name='description',
        ),
    ]
